apiVersion: v1
kind: Service
metadata:
  name: ms1
  namespace: ms1
  labels:
    app: ms1-app
spec:
  selector:
    app: ms1-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-deployment
  namespace: ms1
  labels:
    app: ms1-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms1-app
  template:
    metadata:
      labels:
        app: ms1-app
    spec:
      containers:
      - name: nginx
        image: 005488327456.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
        ports:
        - containerPort: 80

